### ISSUE TITLE
rsync command

### ISSUE THREAD

**Issue by z--m-n** [willmorrison1/sync-obs#1]
Will, I suggest to change the rsync command for the Paris campaign. 

`rsync -e 'ssh -oBatchMode=yes'   -rt -l -D  --compress  --compress-level=7 --append-verify --update  --no-owner --no-group  --no-perms --chmod=ugo=rwX`

#### Future request:
- [x] define the rsync command in the config file
- [x] for transfer of compressed binary files, such as the CL61, we could skip compression in rsync or use a default compression level.

**Comment by willmorrison1** [comment]
> for transfer of compressed binary files, such as the CL61, we could skip compression in rsync or use a default compression level.

happy to keep as is. getting speedup > 1 which I assume has something to do with the compression. With compression:

```
(base) smurobs@meteopi-50f4:~/archive $ journalctl -eu sync_obs.service
Sep 04 20:37:47 meteopi-50f4 python3[26618]: sending incremental file list
Sep 04 20:37:47 meteopi-50f4 python3[26618]: delta-transmission enabled
Sep 04 20:37:47 meteopi-50f4 python3[26618]: T3250605_20220904_203445.nc
Sep 04 20:37:48 meteopi-50f4 python3[26618]: total: matches=0  hash_hits=0  false_alarms=0 data=1172190
Sep 04 20:37:49 meteopi-50f4 python3[26618]: sent 1,002,515 bytes  received 66 bytes  401,032.40 bytes/sec
Sep 04 20:37:49 meteopi-50f4 python3[26618]: total size is 1,172,190  speedup is 1.17
```

without compression e.g.

```
Sep 04 20:54:52 meteopi-50f4 python3[26928]: total: matches=0  hash_hits=0  false_alarms=0 data=1160766
Sep 04 20:54:53 meteopi-50f4 python3[26928]: sent 1,161,154 bytes  received 66 bytes  331,777.14 bytes/sec
Sep 04 20:54:53 meteopi-50f4 python3[26928]: total size is 1,160,766  speedup is 1.00
Sep 04 20:54:53 meteopi-50f4 python3[26931]: opening connection using: ssh -oBatchMode=yes -l datagate5 gateway.meteo.uni-freiburg.de rsync --server -vvulDtre.iLsfxCIvu --a>

```

**Comment by z--m-n** [comment]
Speedup should be related to compression. The same ceilometer files are added to a retention backup with `lzma` compression it's compression ratio is in line with (the inverse of) the speedup found here.
